// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ItemLoginAttachment {
    fileName?: pulumi.Input<string>;
    /**
     * Identifier.
     */
    id?: pulumi.Input<string>;
    size?: pulumi.Input<string>;
    sizeName?: pulumi.Input<string>;
    url?: pulumi.Input<string>;
}

export interface ItemLoginField {
    /**
     * Value of a boolean field.
     */
    boolean?: pulumi.Input<boolean>;
    /**
     * Value of a hidden text field.
     */
    hidden?: pulumi.Input<string>;
    /**
     * Value of a linked field.
     */
    linked?: pulumi.Input<string>;
    /**
     * Name of the field.
     */
    name: pulumi.Input<string>;
    /**
     * Value of a text field.
     */
    text?: pulumi.Input<string>;
}

export interface ItemLoginUri {
    /**
     * URI Match
     */
    match?: pulumi.Input<string>;
    /**
     * URI Value
     */
    value: pulumi.Input<string>;
}

export interface ItemSecureNoteAttachment {
    fileName?: pulumi.Input<string>;
    /**
     * Identifier.
     */
    id?: pulumi.Input<string>;
    size?: pulumi.Input<string>;
    sizeName?: pulumi.Input<string>;
    url?: pulumi.Input<string>;
}

export interface ItemSecureNoteField {
    /**
     * Value of a boolean field.
     */
    boolean?: pulumi.Input<boolean>;
    /**
     * Value of a hidden text field.
     */
    hidden?: pulumi.Input<string>;
    /**
     * Value of a linked field.
     */
    linked?: pulumi.Input<string>;
    /**
     * Name of the field.
     */
    name: pulumi.Input<string>;
    /**
     * Value of a text field.
     */
    text?: pulumi.Input<string>;
}
