// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface GetItemLoginAttachment {
    fileName: string;
    /**
     * Identifier.
     */
    id: string;
    size: string;
    sizeName: string;
    url: string;
}

export interface GetItemLoginField {
    boolean?: boolean;
    hidden?: string;
    linked?: string;
    /**
     * Name.
     */
    name: string;
    text?: string;
}

export interface GetItemLoginUri {
    match?: string;
    value: string;
}

export interface GetItemSecureNoteAttachment {
    fileName: string;
    /**
     * Identifier.
     */
    id: string;
    size: string;
    sizeName: string;
    url: string;
}

export interface GetItemSecureNoteField {
    boolean?: boolean;
    hidden?: string;
    linked?: string;
    /**
     * Name.
     */
    name: string;
    text?: string;
}

export interface ItemLoginAttachment {
    fileName: string;
    /**
     * Identifier.
     */
    id: string;
    size: string;
    sizeName: string;
    url: string;
}

export interface ItemLoginField {
    /**
     * Value of a boolean field.
     */
    boolean?: boolean;
    /**
     * Value of a hidden text field.
     */
    hidden?: string;
    /**
     * Value of a linked field.
     */
    linked?: string;
    /**
     * Name of the field.
     */
    name: string;
    /**
     * Value of a text field.
     */
    text?: string;
}

export interface ItemLoginUri {
    /**
     * URI Match
     */
    match?: string;
    /**
     * URI Value
     */
    value: string;
}

export interface ItemSecureNoteAttachment {
    fileName: string;
    /**
     * Identifier.
     */
    id: string;
    size: string;
    sizeName: string;
    url: string;
}

export interface ItemSecureNoteField {
    /**
     * Value of a boolean field.
     */
    boolean?: boolean;
    /**
     * Value of a hidden text field.
     */
    hidden?: string;
    /**
     * Value of a linked field.
     */
    linked?: string;
    /**
     * Name of the field.
     */
    name: string;
    /**
     * Value of a text field.
     */
    text?: string;
}

