// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Use this data source to get information on an existing Login.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as bitwarden from "@pulumi/bitwarden";
 *
 * const databaseCredentials = bitwarden.getItemLogin({
 *     id: "ec4e447f-9aed-4203-b834-c8f3848828f7",
 * });
 * ```
 */
export function getItemLogin(args: GetItemLoginArgs, opts?: pulumi.InvokeOptions): Promise<GetItemLoginResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("bitwarden:index/getItemLogin:getItemLogin", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getItemLogin.
 */
export interface GetItemLoginArgs {
    /**
     * Identifier.
     */
    id: string;
}

/**
 * A collection of values returned by getItemLogin.
 */
export interface GetItemLoginResult {
    /**
     * List of item attachments.
     */
    readonly attachments: outputs.GetItemLoginAttachment[];
    /**
     * Identifier of the collections the item belongs to.
     */
    readonly collectionIds: string[];
    /**
     * Date the item was created.
     */
    readonly creationDate: string;
    /**
     * Date the item was deleted.
     */
    readonly deletedDate: string;
    /**
     * Mark as a Favorite to have item appear at the top of your Vault in the UI.
     */
    readonly favorite: boolean;
    /**
     * Extra fields.
     */
    readonly fields: outputs.GetItemLoginField[];
    /**
     * Identifier of the folder.
     */
    readonly folderId: string;
    /**
     * Identifier.
     */
    readonly id: string;
    /**
     * Name.
     */
    readonly name: string;
    /**
     * Notes.
     */
    readonly notes: string;
    readonly object: string;
    /**
     * Identifier of the organization.
     */
    readonly organizationId: string;
    /**
     * Login password.
     */
    readonly password: string;
    /**
     * Require master password “re-prompt” when displaying secret in the UI.
     */
    readonly reprompt: boolean;
    /**
     * Last time the item was updated.
     */
    readonly revisionDate: string;
    /**
     * Verification code.
     */
    readonly totp: string;
    readonly type: number;
    /**
     * URI.
     */
    readonly uris: outputs.GetItemLoginUri[];
    /**
     * Login username.
     */
    readonly username: string;
}
/**
 * Use this data source to get information on an existing Login.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as bitwarden from "@pulumi/bitwarden";
 *
 * const databaseCredentials = bitwarden.getItemLogin({
 *     id: "ec4e447f-9aed-4203-b834-c8f3848828f7",
 * });
 * ```
 */
export function getItemLoginOutput(args: GetItemLoginOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetItemLoginResult> {
    return pulumi.output(args).apply((a: any) => getItemLogin(a, opts))
}

/**
 * A collection of arguments for invoking getItemLogin.
 */
export interface GetItemLoginOutputArgs {
    /**
     * Identifier.
     */
    id: pulumi.Input<string>;
}
