// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Use this data source to get information on an existing Secure Note.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as bitwarden from "@pulumi/bitwarden";
 *
 * const sshNotes = bitwarden.getItemSecureNote({
 *     id: "a9e19f26-1b8c-4568-bc09-191e2cf56ed6",
 * });
 * ```
 */
export function getItemSecureNote(args: GetItemSecureNoteArgs, opts?: pulumi.InvokeOptions): Promise<GetItemSecureNoteResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("bitwarden:index/getItemSecureNote:getItemSecureNote", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getItemSecureNote.
 */
export interface GetItemSecureNoteArgs {
    /**
     * Identifier.
     */
    id: string;
}

/**
 * A collection of values returned by getItemSecureNote.
 */
export interface GetItemSecureNoteResult {
    /**
     * List of item attachments.
     */
    readonly attachments: outputs.GetItemSecureNoteAttachment[];
    /**
     * Identifier of the collections the item belongs to.
     */
    readonly collectionIds: string[];
    /**
     * Date the item was created.
     */
    readonly creationDate: string;
    /**
     * Date the item was deleted.
     */
    readonly deletedDate: string;
    /**
     * Mark as a Favorite to have item appear at the top of your Vault in the UI.
     */
    readonly favorite: boolean;
    /**
     * Extra fields.
     */
    readonly fields: outputs.GetItemSecureNoteField[];
    /**
     * Identifier of the folder.
     */
    readonly folderId: string;
    /**
     * Identifier.
     */
    readonly id: string;
    /**
     * Name.
     */
    readonly name: string;
    /**
     * Notes.
     */
    readonly notes: string;
    readonly object: string;
    /**
     * Identifier of the organization.
     */
    readonly organizationId: string;
    /**
     * Require master password “re-prompt” when displaying secret in the UI.
     */
    readonly reprompt: boolean;
    /**
     * Last time the item was updated.
     */
    readonly revisionDate: string;
    readonly type: number;
}
/**
 * Use this data source to get information on an existing Secure Note.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as bitwarden from "@pulumi/bitwarden";
 *
 * const sshNotes = bitwarden.getItemSecureNote({
 *     id: "a9e19f26-1b8c-4568-bc09-191e2cf56ed6",
 * });
 * ```
 */
export function getItemSecureNoteOutput(args: GetItemSecureNoteOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetItemSecureNoteResult> {
    return pulumi.output(args).apply((a: any) => getItemSecureNote(a, opts))
}

/**
 * A collection of arguments for invoking getItemSecureNote.
 */
export interface GetItemSecureNoteOutputArgs {
    /**
     * Identifier.
     */
    id: pulumi.Input<string>;
}
