// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Manages a Vault Login item.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as bitwarden from "@maienm/pulumi-bitwarden";
 *
 * const administrative_user = new bitwarden.ItemLogin("administrative-user", {
 *     collectionIds: ["c74d6067-50b0-4427-bec8-483f3270fde3"],
 *     favorite: true,
 *     fields: [
 *         {
 *             name: "this-is-a-text-field",
 *             text: "text-value",
 *         },
 *         {
 *             boolean: true,
 *             name: "this-is-a-boolean-field",
 *         },
 *         {
 *             hidden: "text-value",
 *             name: "this-is-a-hidden-field",
 *         },
 *     ],
 *     folderId: "3b985a2f-0eed-461e-a5ac-adf5015b00c4",
 *     notes: "<sensitive>",
 *     organizationId: "54421e78-95cb-40c4-a257-17231a7b6207",
 *     password: "<sensitive>",
 *     totp: "<sensitive>",
 *     username: "admin",
 * });
 * ```
 *
 * ## Import
 *
 * Find the identifier of the resource you want to import# $ bw list items --search "Mysql Root Credentials" | jq
 *
 * '.[] .id' ? Master password[hidden] # > "ec4e447f-9aed-4203-b834-c8f3848828f7" # Provide this identifier to Terraform
 *
 * ```sh
 *  $ pulumi import bitwarden:index/itemLogin:ItemLogin administrative-user ec4e447f-9aed-4203-b834-c8f3848828f7
 * ```
 */
export class ItemLogin extends pulumi.CustomResource {
    /**
     * Get an existing ItemLogin resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ItemLoginState, opts?: pulumi.CustomResourceOptions): ItemLogin {
        return new ItemLogin(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'bitwarden:index/itemLogin:ItemLogin';

    /**
     * Returns true if the given object is an instance of ItemLogin.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ItemLogin {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ItemLogin.__pulumiType;
    }

    /**
     * List of item attachments.
     */
    public /*out*/ readonly attachments!: pulumi.Output<outputs.ItemLoginAttachment[]>;
    /**
     * Identifier of the collections the item belongs to.
     */
    public readonly collectionIds!: pulumi.Output<string[] | undefined>;
    /**
     * Date the item was created.
     */
    public /*out*/ readonly creationDate!: pulumi.Output<string>;
    /**
     * Date the item was deleted.
     */
    public /*out*/ readonly deletedDate!: pulumi.Output<string>;
    /**
     * Mark as a Favorite to have item appear at the top of your Vault in the UI.
     */
    public readonly favorite!: pulumi.Output<boolean | undefined>;
    /**
     * Extra fields.
     */
    public readonly fields!: pulumi.Output<outputs.ItemLoginField[] | undefined>;
    /**
     * Identifier of the folder.
     */
    public readonly folderId!: pulumi.Output<string | undefined>;
    /**
     * Name.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Notes.
     */
    public readonly notes!: pulumi.Output<string | undefined>;
    /**
     * INTERNAL USE
     */
    public /*out*/ readonly object!: pulumi.Output<string>;
    /**
     * Identifier of the organization.
     */
    public readonly organizationId!: pulumi.Output<string | undefined>;
    /**
     * Login password.
     */
    public readonly password!: pulumi.Output<string | undefined>;
    /**
     * Require master password “re-prompt” when displaying secret in the UI.
     */
    public readonly reprompt!: pulumi.Output<boolean | undefined>;
    /**
     * Last time the item was updated.
     */
    public /*out*/ readonly revisionDate!: pulumi.Output<string>;
    /**
     * Verification code.
     */
    public readonly totp!: pulumi.Output<string | undefined>;
    /**
     * INTERNAL USE
     */
    public /*out*/ readonly type!: pulumi.Output<number>;
    /**
     * URI.
     */
    public readonly uris!: pulumi.Output<outputs.ItemLoginUri[] | undefined>;
    /**
     * Login username.
     */
    public readonly username!: pulumi.Output<string | undefined>;

    /**
     * Create a ItemLogin resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ItemLoginArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ItemLoginArgs | ItemLoginState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ItemLoginState | undefined;
            resourceInputs["attachments"] = state ? state.attachments : undefined;
            resourceInputs["collectionIds"] = state ? state.collectionIds : undefined;
            resourceInputs["creationDate"] = state ? state.creationDate : undefined;
            resourceInputs["deletedDate"] = state ? state.deletedDate : undefined;
            resourceInputs["favorite"] = state ? state.favorite : undefined;
            resourceInputs["fields"] = state ? state.fields : undefined;
            resourceInputs["folderId"] = state ? state.folderId : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["notes"] = state ? state.notes : undefined;
            resourceInputs["object"] = state ? state.object : undefined;
            resourceInputs["organizationId"] = state ? state.organizationId : undefined;
            resourceInputs["password"] = state ? state.password : undefined;
            resourceInputs["reprompt"] = state ? state.reprompt : undefined;
            resourceInputs["revisionDate"] = state ? state.revisionDate : undefined;
            resourceInputs["totp"] = state ? state.totp : undefined;
            resourceInputs["type"] = state ? state.type : undefined;
            resourceInputs["uris"] = state ? state.uris : undefined;
            resourceInputs["username"] = state ? state.username : undefined;
        } else {
            const args = argsOrState as ItemLoginArgs | undefined;
            resourceInputs["collectionIds"] = args ? args.collectionIds : undefined;
            resourceInputs["favorite"] = args ? args.favorite : undefined;
            resourceInputs["fields"] = args?.fields ? pulumi.secret(args.fields) : undefined;
            resourceInputs["folderId"] = args ? args.folderId : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["notes"] = args?.notes ? pulumi.secret(args.notes) : undefined;
            resourceInputs["organizationId"] = args ? args.organizationId : undefined;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["reprompt"] = args ? args.reprompt : undefined;
            resourceInputs["totp"] = args?.totp ? pulumi.secret(args.totp) : undefined;
            resourceInputs["uris"] = args ? args.uris : undefined;
            resourceInputs["username"] = args?.username ? pulumi.secret(args.username) : undefined;
            resourceInputs["attachments"] = undefined /*out*/;
            resourceInputs["creationDate"] = undefined /*out*/;
            resourceInputs["deletedDate"] = undefined /*out*/;
            resourceInputs["object"] = undefined /*out*/;
            resourceInputs["revisionDate"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["fields", "notes", "password", "totp", "username"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(ItemLogin.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ItemLogin resources.
 */
export interface ItemLoginState {
    /**
     * List of item attachments.
     */
    attachments?: pulumi.Input<pulumi.Input<inputs.ItemLoginAttachment>[]>;
    /**
     * Identifier of the collections the item belongs to.
     */
    collectionIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Date the item was created.
     */
    creationDate?: pulumi.Input<string>;
    /**
     * Date the item was deleted.
     */
    deletedDate?: pulumi.Input<string>;
    /**
     * Mark as a Favorite to have item appear at the top of your Vault in the UI.
     */
    favorite?: pulumi.Input<boolean>;
    /**
     * Extra fields.
     */
    fields?: pulumi.Input<pulumi.Input<inputs.ItemLoginField>[]>;
    /**
     * Identifier of the folder.
     */
    folderId?: pulumi.Input<string>;
    /**
     * Name.
     */
    name?: pulumi.Input<string>;
    /**
     * Notes.
     */
    notes?: pulumi.Input<string>;
    /**
     * INTERNAL USE
     */
    object?: pulumi.Input<string>;
    /**
     * Identifier of the organization.
     */
    organizationId?: pulumi.Input<string>;
    /**
     * Login password.
     */
    password?: pulumi.Input<string>;
    /**
     * Require master password “re-prompt” when displaying secret in the UI.
     */
    reprompt?: pulumi.Input<boolean>;
    /**
     * Last time the item was updated.
     */
    revisionDate?: pulumi.Input<string>;
    /**
     * Verification code.
     */
    totp?: pulumi.Input<string>;
    /**
     * INTERNAL USE
     */
    type?: pulumi.Input<number>;
    /**
     * URI.
     */
    uris?: pulumi.Input<pulumi.Input<inputs.ItemLoginUri>[]>;
    /**
     * Login username.
     */
    username?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ItemLogin resource.
 */
export interface ItemLoginArgs {
    /**
     * Identifier of the collections the item belongs to.
     */
    collectionIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Mark as a Favorite to have item appear at the top of your Vault in the UI.
     */
    favorite?: pulumi.Input<boolean>;
    /**
     * Extra fields.
     */
    fields?: pulumi.Input<pulumi.Input<inputs.ItemLoginField>[]>;
    /**
     * Identifier of the folder.
     */
    folderId?: pulumi.Input<string>;
    /**
     * Name.
     */
    name?: pulumi.Input<string>;
    /**
     * Notes.
     */
    notes?: pulumi.Input<string>;
    /**
     * Identifier of the organization.
     */
    organizationId?: pulumi.Input<string>;
    /**
     * Login password.
     */
    password?: pulumi.Input<string>;
    /**
     * Require master password “re-prompt” when displaying secret in the UI.
     */
    reprompt?: pulumi.Input<boolean>;
    /**
     * Verification code.
     */
    totp?: pulumi.Input<string>;
    /**
     * URI.
     */
    uris?: pulumi.Input<pulumi.Input<inputs.ItemLoginUri>[]>;
    /**
     * Login username.
     */
    username?: pulumi.Input<string>;
}
